name: Test Commec DBs

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Force full pull of LFS files
        run: git lfs pull

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: commec-env
          environment-file: tests/environment.yaml
          auto-activate-base: false

      - name: Test hmmscan installed.
        shell: bash -l {0}
        run: hmmscan -h

      - name: Hash all database files recursively.
        shell: bash -l {0}
        run: |
          find commec-dbs/*/* -type f -exec sha256sum {} +

      - name: Run tests
        shell: bash -l {0}
        run: pytest tests/ -vv
