name: Test Commec DBs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: commec-env
          environment-file: tests/environment.yaml
          auto-activate-base: false

      - name: Run tests
        shell: bash -l {0}
        run: pytest tests/
