name: Automated Release with ZIP

on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout full repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true  # Also pulls Git LFS files

    - name: Set up Git LFS (redundant safety)
      run: |
        git lfs install
        git lfs pull

    - name: Create ZIP from commec-dbs subdirectory
      run: zip -r commec-dbs.zip commec-dbs

    - name: Create GitHub Release and upload ZIP
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: commec-dbs.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
